apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mine-klager-microfrontend
  namespace: klage
  labels:
    team: klage
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /api/internal/isAlive
    initialDelay: 5
  readiness:
    path: /api/internal/isReady
    initialDelay: 5
  replicas:
    min: 2
    max: 4
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
          namespace: min-side
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: "10m"
      memory: 32Mi
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /var/run
    - emptyDir:
        medium: Memory
      mountPath: /var/lib/nginx/tmp
