apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mine-klager-microfrontend
  namespace: klage
  labels:
    team: klage
spec:
  tokenx:
    enabled: true
  image: {{ image }}
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 0
    periodSeconds: 2
    timeout: 1
  readiness:
    path: /isReady
    initialDelay: 0
    periodSeconds: 1
    timeout: 1
  replicas:
    min: 2
    max: 2
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
          namespace: min-side
  resources:
    limits:
      memory: 32Mi
    requests:
      cpu: 1m
      memory: 8Mi
