name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev-*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        shell: bash
        env:
          BUN_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: |
          echo -e "\n[install.scopes]\n\"@navikt\" = { token = \"$BUN_AUTH_TOKEN\", url = \"https://npm.pkg.github.com/\" }" >> bunfig.toml
          bun install --frozen-lockfile

      - name: Build
        shell: bash
        env:
          VERSION: ${{ github.sha }}
        run: bun run build

      - name: CDN Upload
        id: cdn-upload
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: klage
          source: ./dist/client/_astro
          destination: mine-klager-microfrontend

      - name: Build and push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: klage

  update-manifest-dev:
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v3.yaml@main
    needs: build
    secrets: inherit
    with:
      id: mine-klager-microfrontend
      url: http://mine-klager-microfrontend.klage
      appname: mine-klager-microfrontend
      namespace: klage
      cluster: dev-gcp
      commitmsg: ${{ github.event.head_commit.message }}
      fallback: fallback
      ssr: true

  update-manifest-prod:
    if: github.ref == 'refs/heads/main'
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v3.yaml@main
    needs: build
    secrets: inherit
    with:
      id: mine-klager-microfrontend
      url: http://mine-klager-microfrontend.klage
      appname: mine-klager-microfrontend
      namespace: klage
      cluster: prod-gcp
      commitmsg: ${{ github.event.head_commit.message }}
      fallback: fallback
      ssr: true

  deploy-dev:
    needs: [build, update-manifest-dev]
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to dev"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}

  deploy-prod:
    needs: [build, update-manifest-prod]
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to prod"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/prod.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}
