name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev-*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Build Go application
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server .

      - name: Build and push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: klage

  update-manifest-dev:
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v3.yaml@main
    permissions:
      contents: "read"
    needs: build
    secrets: inherit
    with:
      id: mine-klager-microfrontend
      url: http://mine-klager-microfrontend.klage
      appname: mine-klager-microfrontend
      namespace: klage
      cluster: dev-gcp
      commitmsg: ${{ github.event.head_commit.message }}
      fallback: fallback
      ssr: true

  update-manifest-prod:
    if: github.ref == 'refs/heads/main'
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v3.yaml@main
    permissions:
      contents: "read"
    needs: build
    secrets: inherit
    with:
      id: mine-klager-microfrontend
      url: http://mine-klager-microfrontend.klage
      appname: mine-klager-microfrontend
      namespace: klage
      cluster: prod-gcp
      commitmsg: ${{ github.event.head_commit.message }}
      fallback: fallback
      ssr: true

  deploy-dev:
    needs: [build, update-manifest-dev]
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to dev"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}

  deploy-prod:
    needs: [build, update-manifest-prod]
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to prod"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/prod.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}
