name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev-*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"

      - name: Build Go application
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server .

      - name: Build and push
        uses: nais/docker-build-push@423a915c9b72edf2ba848b88171ccb0489e2a40a # v0
        id: docker-build-push
        with:
          team: klage

  update-manifest-dev:
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v3.yaml@71678a4147620d62d582b57fe30e1527b4add74f # main
    permissions:
      contents: "read"
    needs: build
    secrets: inherit
    with:
      id: mine-klager-microfrontend
      url: http://mine-klager-microfrontend.klage
      appname: mine-klager-microfrontend
      namespace: klage
      cluster: dev-gcp
      commitmsg: ${{ github.event.head_commit.message }}
      fallback: fallback
      ssr: true

  update-manifest-prod:
    if: github.ref == 'refs/heads/main'
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v3.yaml@71678a4147620d62d582b57fe30e1527b4add74f # main
    permissions:
      contents: "read"
    needs: build
    secrets: inherit
    with:
      id: mine-klager-microfrontend
      url: http://mine-klager-microfrontend.klage
      appname: mine-klager-microfrontend
      namespace: klage
      cluster: prod-gcp
      commitmsg: ${{ github.event.head_commit.message }}
      fallback: fallback
      ssr: true

  deploy-dev:
    needs: [build, update-manifest-dev]
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@11d5960a326750d5838078e36cf38b85af677262" # v4.4.0
      - name: "Deploy to dev"
        uses: "nais/deploy/actions/deploy@9850be311389ca754d9a9f2280615419d738c891" # v3
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}

  deploy-prod:
    needs: [build, update-manifest-prod]
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@11d5960a326750d5838078e36cf38b85af677262" # v4.4.0
      - name: "Deploy to prod"
        uses: "nais/deploy/actions/deploy@9850be311389ca754d9a9f2280615419d738c891" # v3
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/prod.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}
