name: Manual deploy to dev
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit

  update-manifest-dev:
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v3.yaml@main
    needs: build
    secrets: inherit
    with:
      id: mine-klager-microfrontend
      url: http://mine-klager-microfrontend.klage
      appname: mine-klager-microfrontend
      namespace: klage
      cluster: dev-gcp
      commitmsg: ${{ github.event.head_commit.message }}
      fallback: nb
      ssr: true

  deploy-dev:
    needs: [build, update-manifest-dev]
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to dev"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}
